# Generated by Django 5.1 on 2025-03-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication_Service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
